env:
  global:
  - secure: 0DPb1ibzou9SyBwHDdhbQMlf7kxyaLaaXFeWyvflmWk+6c7BkoOGLEdjC8uSHMX0HCXt0NkRHHUp4qTzTKwV/wX2aVh0DQdQXHQS2nfJeHJtyktsYO5QyfokrahRaX1A9gaCW0kyeElg4D3ah9L0R8HOM0eaO9e5+SZ09dCArGoHonDymQQpxcJ/IPwCiqByba8A1Q721+y4Y/kBZxXl15/UZB6M781goHIHdm/UGcezNM7Oe7gBgXWQu2C+HlR7hxp3rycNxrAX1iuyhesC1uVprprbnsnEVIcWGOo5POLbG79IPrkvVkhKS6sL4a3Xa5kzmlvDnQkFEvFWFpwWoLahdqeXCkfcZ/zN2gnJWauUXrXOqFiHHVr97LMBLG8fveuDECJzrMVPN10rD/cAbt8YXub8XvZ5fV4913JAHl+XB4YDy5KSPCqBG4z9ljRv9gaM022rPFyPKqmBclbK2u/oCXP7lBUWAsuXqsxD69P+Kx8bMrNDuVChWZw4QMOMAAPCq/pi796HCIMYOiAykEuxLqbMbnzFHxsTr+ICdNKQVZ0s7k3eCo8nM8BQnjXqTKu0tDmO0ImdPtjaCIw1AfqYCRTHSWdbbWKlDR9fPJoxYJHsd3h/rcbP0NWbcB1ovA+ESogcKSlHRagVwa51EaWovAQ4ePyY2suiDMkdi8g=
  - secure: qNG3Ni0IvxEJy4RzGWhVR7s2xrXg54qjyaXKaqdmLg4vTvF20LiWGG68sPosrxS98rk6lGL2wTIlsIaLe0MeD6JiF44OO4S8CJfEe2EEEXMXFTI9uV7amYe/kcr8eEdvpFrlUDG+ZnOVYlq6/eYSsew2dqtLj7EyDfSYRvebcbeW1d0aycgjvG2NQyGsjCQzTCCxHcQyHXquwCZWokN5KRWInbQneDPdwlCjq+/DqXtyC3fppXndWdDitUUfGBeHHpb2iIumt3RgHgYpm1FH7T4RrYdxWCrD+krqFNFy9LSg5nuCie4pY1zLeEZ3YrqAsLcBArEHi8k3R3LuJn6xbxh973Omx59A0KQYC/6y6n+1JH0kt41qYFhn0pDsJJbzygGFp6roMYza4IjT/ceY9/4GIGykJInt1Qej/P2C4RCL2S+/ijm53142bmlieEdfTuyjIRg9BGJbzTg8B1D3yMp52jh1YQfvjWNgy81VwKKbf0UmxvOV2Xfgh2jylOldDuwZx9Gg7SDX15ZT+MFDWIQO0LI4FGVMRWS95E2qVqsEN8O+l5n5s0nLXEMk84mPVlWpDZTBC2zoHWr3PepkvJoJmZCOVhoGgqinEpi+NCRfKpE+fLnuy/k9icTQiNLlJNBqJ4/CWhcXUVx4YI01jkYedP9XGw91COWzNVDsFFw=

services:
- docker

addons:
  sonarcloud:
    organization: departement-loire-atlantiqu-1
    token:
      secure: ragbx6x82A4bzYxBg0C9oz6cHnHbPf6dkEtMvN8+IltxoKCO+voUmpIdKE9N1bC2kqNoW2V2igjxbUV4Qh7aqaQRY74XOEpVIBH41J5dZ9gLPcFK++KeUyGW2ND877tpaYz6Wf5uH0ssEXJVJvP9hhE3kPq1eKUgT7UAXckM56MsBpEJ+yyBCTDWlkxyh7RkBIysSKJY4qDrTXC0EbThB2U+hsOTXVRcTj/AoyHmPnqHQ8LwetRjUtqxLP/yMdyZ8sx2Ru9j95NS/k+abanOtImIIwPZmhKkA6Q0eWBUoMUJV6cL2eXlNMHSd/yg+1/aQlUiT/52aWiCLKt26P5DLtWyjj8/b9dAcabOd1Aqyo4dyci7XfXNi4tUYMXKqOvk2Dn9r6V5wR4mKcbf1FyGLDLelbVuDT0curIo+Y4CleBdZKEUTfXx8wUNCz+uEQLjoQdmyaTcYYd+ZNZ9ynkhVVyKzbL3p7FHVX9dfRdrzcBTmQMRlIBc7CZuV3haQpzn3AEwVHXHqk7tbtSGsHRJFdf5YzwJqjx97xfvrBPfqo6XbJwBvagGAuxBYsglm6A8rqCRy3gkBS0/Ud41JPxXSK3uESUDko1OK+UG3gcMaFyFevt3ELkf5yxU924BrtyZ6u3LT0BaiCpwNrJnoWphtbytS1ibHI5p8epoGiAOSsI=

before_script:
- echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
- docker pull julienbayle/jplatformbuild

script:
- docker run -v ${TRAVIS_BUILD_DIR}:/root/source --name buildimage -t julienbayle/jplatformbuild
- docker cp buildimage:/root/dist .
- export CODE_VERSION=`git describe`
- sonar-scanner -Dsonar.projectVersion=$CODE_VERSION

deploy:
  provider: releases
  api_key:
    secure: NzuKuebnWpNIysU9ABtmVlX0VjsWqpy7YUilwnyaIL8hQ65wkA2nRRb2vdDh2AymgDsStO93SCepnO8YDpwmMyda/zgrt1TBJhpU1pSfqfUr+8rXCWgNOXcX5eoqOsolGemapHZ1AqeTmxfZr3RugZe0IENVhktL11guWibhF58PlaKH9/T6fZJxTW2Cr86wVYCxNX8t8KnS+hWwxCJ2X+F1+GUqeE06vUmKFZPUaH5utuVcKres/oJ9LUtY3noYvBDdq+8g+3M0q/2bTpIRMvo7ujv10Q16dOB1T4qcZtTFxsSjUb9h3H5AuQL66QSbh1Lbir50zwdpPpEMt85iujsZZzujVZYsGPYXAHy/Wt7NgvWjPWCbJllbIvLuY8AncvnbFzIgq7MH/ZrbleRM/z3W1qLZuUspQ/23qJN0YBh9WT8LpE3D630+i1FvAqgWBm8gIpLrRGADJSNt+HeJlPJCXI4GgHZsB0E+1drOEJeutpvWeLqIIPiRfszJDVCibDw/GOcYzeRx690nt4BqwEeU7nUh0Fd6GBgmyAMsMKQ58oScdHV6r/4q6Nu54b+LuxpBPDd2bSYk0w1NMSvQgNlDwRIEff4MoJ+Z37NDHmRYZV4rdItcHxFX6TOTG+VNV3U/dO1t8CGNYx7TWy9YQ3KYGUozncap5InNZUyEVxM=
  file: "${TRAVIS_BUILD_DIR}/dist/*.zip"
  skip_cleanup: true
  on:
    tags: true
